function dr_fcn = drFcn(u)
%DRFCN
%    DR_FCN = DRFCN(U)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Sep-2025 16:56:24

dr_fcn = -sin(u.*(1.0./1.0e1));
