function road_fcn = roadFcn(u)
%ROADFCN
%    ROAD_FCN = ROADFCN(U)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Sep-2025 16:56:23

road_fcn = cos(u.*(1.0./1.0e1)).*1.0e1;
